path_to_track: "configs/global-plan/yas_marina_real_race_line_mue_0_5_3_m_margin.json"

visualizer_UI_config:
  log_level: "DEBUG"
  log_items: ["Percieve", "Plan", "Control", "Visualize"]

  plot_items: ["legend", "locations", "global plan", "local plan", "lattice graph", "ego state", "agent state"]

  execution_bridge: "simple_sim"
  execution_control_dt: 0.02
  execution_plan_dt: 0.7
  execution_mode: "synchronous" # synchronous, asynchronous

