default:
  L_f: 2.5
  detector: ground_truth
  device: cuda:0
  exclude: []
  filepath: configs/c10_perception.yaml
  grid_size: 100
  max_acceleration: 10
  max_agent_distance: 50.0
  max_agent_vehicles: 12
  max_steering: 0.7
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
  pred_horizon: 3
  prediction_mode: grid
  predictor: AttentionGMM
  tracker: None
xx:
  L_f: 2.5
  detector: ground_truth
  device: cuda:0
  exclude: []
  filepath: configs/c10_perception.yaml
  grid_size: 100
  max_acceleration: 10
  max_agent_distance: 50.0
  max_agent_vehicles: 12
  max_steering: 0.7
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
  pred_horizon: 3
  prediction_mode: grid
  predictor: AttentionGMM
  tracker: x
