default:
  L_f: 2.5
  exclude: []
  filepath: configs/c10_perception.yaml
  max_acceleration: 10
  max_agent_vehicles: 12
  max_steering: 0.7
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
  device: "cuda:0" #cpu
  max_agent_distance: 50.0 # max distance (memters) of agents to be considered in the prediction 
  detector: "ground_truth"
  tracker: "None"
  predictor:  "AttentionGMM"
  prediction_mode: "grid"  # single multi GMM or grid
  pred_horizon: 3 # this is property of predictor -> how many secs in the future it predicts
xx:
  L_f: 2.5
  exclude: []
  filepath: configs/c10_perception.yaml
  max_acceleration: 10
  max_agent_vehicles: 12
  max_steering: 0.77
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
  device: "cuda:0" #cpu
  max_agent_distance: 50.0 # max distance (memters) of agents to be considered in the prediction 
  detector: "ground_truth"
  tracker: "None"
  predictor:  "AttentionGMM"
  prediction_mode: "grid"  # single multi GMM or grid
  pred_horizon: 3 # this is property of predictor -> how many secs in the future it predicts
