Carla_Town10:
  L_f: 2.5
  default_theta: 0
  exclude: []
  filepath: configs/c10_perception.yaml
  grid_size: 100
  max_acceleration: 10
  max_agent_vehicles: 12
  max_steering: 0.7
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
SAN:
  L_f: 2.5
  default_theta: 0
  exclude: []
  filepath: configs/c10_perception.yaml
  grid_size: 100
  max_acceleration: 10
  max_agent_vehicles: 12
  max_steering: 0.7
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
default:
  L_f: 2.5
  default_theta: 0
  exclude: []
  filepath: configs/c10_perception.yaml
  grid_size: 100
  max_acceleration: 10
  max_agent_vehicles: 12
  max_steering: 0.7
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
perception exp:
  L_f: 2.5
  default_theta: 0
  exclude: []
  filepath: configs/c10_perception.yaml
  grid_size: 100
  max_acceleration: 10
  max_agent_vehicles: 12
  max_steering: 0.7
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
source defaults:
  L_f: 2.5
  default_theta: 0
  exclude: []
  filepath: configs/c10_perception.yaml
  grid_size: 100
  max_acceleration: 10
  max_agent_vehicles: 12
  max_steering: 0.7
  max_valocity: 30
  min_acceleration: -20
  min_steering: -0.7
