default:
  alpha: 0.01
  beta: 0.001
  exclude: []
  filepath: configs/c30_control.yaml
  gamma: 0.6
  k: 5
  k_soft: 0.01
  lookahead: 5
  pid_lookahead: 2
  pid_valpha: 0.8
  pid_vbeta: 0.01
  pid_vgamma: 0.3
  slow_down_cte: 0.5
  slow_down_heading_cte: 0.5235987755982988
  slow_down_vel_threshold: 3
  valpha: 0.8
  vbeta: 0.01
  vgamma: 0.3
xx:
  alpha: 0.01
  beta: 0.001
  exclude: []
  filepath: configs/c30_control.yaml
  gamma: 0.6
  k: 5
  k_soft: 0.01
  lookahead: 5
  pid_lookahead: 2
  pid_valpha: 0.8
  pid_vbeta: 0.01
  pid_vgamma: 0.3
  slow_down_cte: 0.5
  slow_down_heading_cte: 0.5235987755982988
  slow_down_vel_threshold: 3
  valpha: 0.8
  vbeta: 0.01
  vgamma: 0.3
