B:
  async_mode: false
  bridge: BasicSim
  control_dt: 0.05
  controller: StanleyController
  filepath: configs/c40_execution.yaml
  global_planner: RaceGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: RNDPlanner
  perception: ''
  replan_dt: 0.5
  sim_dt: 0.01
Carla_Town10:
  async_mode: true
  bridge: CarlaBridge
  control_dt: 0.01
  controller: StanleyController
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: RNDPlanner
  perception: MultiObjectPredictor
  replan_dt: 5.0
  sim_dt: 0.011
SAN:
  async_mode: true
  bridge: BasicSim
  control_dt: 0.01
  controller: StanleyController
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/san_campus.xodr
  local_planner: RNDPlanner
  perception: MultiObjectPredictor
  replan_dt: 0.5
  sim_dt: 0.01
default:
  async_mode: true
  bridge: BasicSim
  control_dt: 0.01
  controller: StanleyController
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: RNDPlanner
  perception: MultiObjectPredictor
  replan_dt: 0.55
  sim_dt: 0.011
perception exp:
  async_mode: false
  bridge: BasicSim
  control_dt: 0.01
  controller: StanleyController
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: RNDPlanner
  perception: MultiObjectPredictor
  replan_dt: 0.55
  sim_dt: 0.011
