B:
  async_mode: false
  bridge: BasicSim
  control_dt: 0.05
  controller: StanleyController
  filepath: configs/c40_execution.yaml
  global_planner: RaceGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: RNDPlanner
  perception: ''
  replan_dt: 0.5
  sim_dt: 0.01
Carla_Town10:
  async_mode: true
  bridge: CarlaBridge
  community_extensions:
    delete_me: /home/mkhonji/Dropbox/20-development/21-software-dev/21.2-AVlite/avlite-plugins/delete_me
  control_dt: 0.01
  controller: StanleyController
  default_extensions:
  - executer_multi_processing
  - test_ext
  - multi_object_prediction
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: RNDPlanner
  perception: MultiObjectPredictor
  replan_dt: 5.0
  sim_dt: 0.011
SAN:
  async_mode: true
  bridge: BasicSim
  community_extensions:
    delete_me: /home/mkhonji/Dropbox/20-development/21-software-dev/21.2-AVlite/avlite-plugins/delete_me
  control_dt: 0.01
  controller: StanleyController
  default_extensions:
  - executer_multi_processing
  - test_ext
  - multi_object_prediction
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/san_campus.xodr
  local_planner: RNDPlanner
  perception: MultiObjectPredictor
  replan_dt: 0.5
  sim_dt: 0.01
default:
  basic_sim_default_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  basic_sim_npc_control: true
  basic_sim_npc_speed_factor: 0.8
  bridge: BasicSim
  community_extensions:
    delete_me: /home/mkhonji/Dropbox/20-development/21-software-dev/21.2-AVlite/avlite-plugins/delete_me
  control_dt: 0.01
  controller: StanleyController
  default_extensions:
  - executer_multi_processing
  - test_ext
  - executer_ros
  - multi_object_prediction
  executer_type: AsyncThreadedExecuter
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: GreedyLatticePlanner
  perception: MultiObjectPredictor
  perception_dt: 0.5
  replan_dt: 0.55
  sim_dt: 0.011
perception exp:
  basic_sim_default_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  basic_sim_npc_control: true
  basic_sim_npc_speed_factor: 0.8
  bridge: BasicSim
  community_extensions:
    new_plugin: /home/mkhonji/Desktop/new_plugin
  control_dt: 0.01
  controller: StanleyController
  default_extensions:
  - executer_multi_processing
  - multi_object_prediction
  - test_ext
  - ros_executer
  executer_type: AsyncThreadedExecuter
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: GreedyLatticePlanner
  perception: testClass
  perception_dt: 0.5
  replan_dt: 0.55
  sim_dt: 0.011
ros:
  basic_sim_default_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  basic_sim_npc_control: true
  basic_sim_npc_speed_factor: 0.8
  bridge: BasicSim
  community_extensions:
    delete_me: /home/mkhonji/Dropbox/20-development/21-software-dev/21.2-AVlite/avlite-plugins/delete_me
  control_dt: 0.01
  controller: StanleyController
  default_extensions:
  - executer_multi_processing
  - test_ext
  - executer_ros
  - multi_object_prediction
  executer_type: ROSExecuter
  filepath: configs/c40_execution.yaml
  global_planner: HDMapGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/Town10HD_Opt.xodr
  local_planner: GreedyLatticePlanner
  perception: testClass
  perception_dt: 0.5
  replan_dt: 0.55
  sim_dt: 0.011
source defaults:
  async_mode: false
  bridge: BasicSim
  control_dt: 0.05
  controller: StanleyController
  filepath: configs/c40_execution.yaml
  global_planner: RaceGlobalPlanner
  global_trajectory: data/yas_marina_real_race_line_mue_0_5_3_m_margin.json
  hd_map: data/san_campus.xodr
  local_planner: GreedyLatticePlanner
  perception: ''
  replan_dt: 0.5
  sim_dt: 0.01
