async_exec: false
bg_color: '#333333'
control_dt: 0.01
dark_mode: true
disable_log: false
enable_joystick: true
exec_control: true
exec_perceive: false
exec_plan: true
execution_bridge: Basic
fg_color: white
frenet_view_follow_planner: false
frenet_zoom: 260
global_plan_view: true
global_planner_type: GlobalHDMapPlanner
global_view_follow_planner: false
local_plan_view: false
local_planner_type: RNDPlanner
log_level: DEBUG
perception_status_text: Click on the plot.
replan_dt: 0.01
shortcut_mode: false
show_control_logs: false
show_execute_logs: true
show_global_plan: true
show_legend: false
show_local_lattice: true
show_local_plan: true
show_past_locations: true
show_perceive_logs: false
show_plan_logs: false
show_state: true
show_tools_logs: true
show_vis_logs: true
sim_dt: 0.01
xy_zoom: 810
