default:
  async_exec: true
  bg_color: '#333333'
  control_dt: 0.01
  controller_type: StanleyController
  dark_mode: true
  disable_log: false
  enable_joystick: true
  exec_control: true
  exec_perceive: true
  exec_plan: true
  execution_bridge: Basic
  fg_color: white
  frenet_view_follow_planner: false
  frenet_zoom: 30
  global_plan_view: true
  global_planner_type: HDMapGlobalPlanner
  global_view_follow_planner: false
  global_zoom: 70
  local_plan_view: true
  local_planner_type: RNDPlanner
  log_level: INFO
  replan_dt: 0.5
  selected_profile: default
  shortcut_mode: false
  show_control_logs: true
  show_execute_logs: true
  show_global_plan: true
  show_legend: false
  show_local_lattice: true
  show_local_plan: true
  show_past_locations: true
  show_perceive_logs: true
  show_plan_logs: true
  show_state: true
  show_tools_logs: true
  show_vis_logs: true
  sim_dt: 0.01
  xy_zoom: 30
xx:
  async_exec: true
  bg_color: '#333333'
  control_dt: 0.01
  controller_type: StanleyController
  dark_mode: true
  disable_log: false
  enable_joystick: true
  exec_control: true
  exec_perceive: true
  exec_plan: true
  execution_bridge: Basic
  fg_color: white
  frenet_view_follow_planner: false
  frenet_zoom: 30
  global_plan_view: true
  global_planner_type: HDMapGlobalPlanner
  global_view_follow_planner: false
  global_zoom: 70
  local_plan_view: true
  local_planner_type: RNDPlanner
  log_level: INFO
  replan_dt: 0.5
  selected_profile: xx
  shortcut_mode: false
  show_control_logs: true
  show_execute_logs: true
  show_global_plan: true
  show_legend: false
  show_local_lattice: true
  show_local_plan: true
  show_past_locations: true
  show_perceive_logs: true
  show_plan_logs: true
  show_state: true
  show_tools_logs: true
  show_vis_logs: true
  sim_dt: 0.011
  xy_zoom: 30
