async_exec: true
control_dt: 0.02
control_fps: '  48.3'
current_wp: '34'
dark_mode: true
disable_log: true
elapsed_real_time: '  0.00'
elapsed_sim_time: '  0.00'
exec_control: true
exec_option: Basic
exec_perceive: true
exec_plan: true
exec_running: false
frenet_view_follow_planner: false
frenet_zoom: 30
global_plan_view: false
global_view_follow_planner: false
lap: '    0'
log_level: STDOUT
replan_dt: 0.01
replan_fps: '   1.9'
shortcut_mode: false
show_control_logs: true
show_execute_logs: true
show_global_plan: true
show_legend: false
show_local_lattice: true
show_local_plan: true
show_past_locations: true
show_perceive_logs: true
show_plan_logs: true
show_state: true
show_vis_logs: true
sim_dt: 0.01
vehicle_state: "Loc: (+372.00, -747.49),\nVel: 19.39 ( 69.81 km/h),\n\u03B8:  -0.0"
xy_zoom: 30
