async_exec: true
bg_color: '#333333'
control_dt: 0.01
controller_type: StanleyController
dark_mode: true
disable_log: false
enable_joystick: true
exec_control: true
exec_perceive: false
exec_plan: true
execution_bridge: Basic
fg_color: white
frenet_view_follow_planner: false
frenet_zoom: 60
global_plan_view: true
global_planner_type: HDMapGlobalPlanner
global_view_follow_planner: false
global_zoom: 240
local_plan_view: true
local_planner_type: RNDPlanner
log_level: INFO
perception_status_text: Click on the plot.
replan_dt: 500000.0
shortcut_mode: false
show_control_logs: true
show_execute_logs: false
show_global_plan: true
show_legend: false
show_local_lattice: false
show_local_plan: true
show_past_locations: true
show_perceive_logs: false
show_plan_logs: false
show_state: true
show_tools_logs: false
show_vis_logs: false
sim_dt: 0.01
xy_zoom: 30
