Carla_Town10:
  detector: ground_truth
  device: cuda:0
  max_agent_distance: 50.0
  pred_horizon: 3
  prediction_mode: grid
  predictor: AttentionGMM
  tracker: None
SAN:
  detector: ground_truth
  device: cuda:0
  max_agent_distance: 50.0
  pred_horizon: 3
  prediction_mode: grid
  predictor: AttentionGMM
  tracker: None
default:
  detector: ground_truth
  device: cuda:0
  max_agent_distance: 50.0
  pred_horizon: 3
  prediction_mode: grid
  predictor: AttentionGMM
  tracker: None
perception exp:
  detector: ground_truth
  device: cuda:0
  max_agent_distance: 50.0
  pred_horizon: 3
  prediction_mode: grid
  predictor: AttentionGMM
  tracker: None
ros:
  detector: ground_truth
  device: cuda:0
  max_agent_distance: 50.0
  pred_horizon: 3
  prediction_mode: grid
  predictor: AttentionGMM
  tracker: None
source defaults:
  detector: ground_truth
  device: cuda:0
  max_agent_distance: 50.0
  pred_horizon: 3
  prediction_mode: grid
  predictor: AttentionGMM
  tracker: None
